import json
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

url = "https://ollamaraul-70516613071.us-east4.run.app/api/chat"

payload = {
    "model": "qwen3-coder:30b",
    "messages": [
        {
            "role": "user",
            "content": 
"""
with the next table definitions:
create or replace TRANSIENT TABLE DA_PRD_V1.DA_DW.DIM_SUBSCRIPTION_NEW (
	SUBSCRIPTION_ID VARCHAR(32),
	CUSTOMER_ID VARCHAR(32),
	INVOICE_OWNER_ID VARCHAR(32),
	PARENT_CUSTOMER_ID VARCHAR(32),
	PAYMENT_METHOD_ID VARCHAR(32),
	CLUB_OF_PURCHASE_ID VARCHAR(32),
	CLUB_OF_REVENUE_ID VARCHAR(32),
	EMPLOYEE_ID VARCHAR(32),
	MAIN_RATEPLAN_ID VARCHAR(32),
	MAIN_PRODUCT_ID VARCHAR(32),
	SUBSCRIPTION_SRC_ID VARCHAR(255),
	CUSTOMER_SRC_ID VARCHAR(255),
	INVOICE_OWNER_SRC_ID VARCHAR(255),
	PARENT_CUSTOMER_SRC_ID VARCHAR(255),
	PAYMENT_METHOD_SRC_ID VARCHAR(255),
	CLUB_OF_REVENUE_SRC_ID VARCHAR(16777216),
	CLUB_OF_PURCHASE_SRC_ID VARCHAR(255),
	EMPLOYEE_SRC_ID VARCHAR(255),
	SUBSCRIPTION_SRC_NUM VARCHAR(255),
	MAIN_RATEPLAN_SRC_ID VARCHAR(255),
	MAIN_PRODUCT_SRC_ID VARCHAR(255),
	ORIGINAL_SUBSCRIPTION_SRC_ID VARCHAR(255),
	ACCOUNTID VARCHAR(255),
	DEFAULTPAYMENTMETHODID VARCHAR(255),
	PARENTACCOUNTID VARCHAR(255),
	SUBSCRIPTION_VERSION NUMBER(12,0),
	IS_AUTO_RENEW BOOLEAN,
	IS_DELETED BOOLEAN,
	CANCELLED_DATE TIMESTAMP_NTZ(9),
	CANCELLED_DATE_UTC TIMESTAMP_NTZ(9),
	ACCEPTANCE_DATE TIMESTAMP_NTZ(9),
	ACCEPTANCE_DATE_UTC TIMESTAMP_NTZ(9),
	EFFECTIVE_DATE TIMESTAMP_NTZ(9),
	EFFECTIVE_DATE_UTC TIMESTAMP_NTZ(9),
	EFFECTIVE_DATE_ID NUMBER(38,0),
	CREATE_SRC_DATE TIMESTAMP_NTZ(9),
	CREATE_DATE_UTC TIMESTAMP_NTZ(9),
	UPDATE_SRC_DATE TIMESTAMP_NTZ(9),
	UPDATE_DATE_UTC TIMESTAMP_NTZ(9),
	CURRENT_TERM NUMBER(12,0),
	CURRENT_TERM_PERIOD_TYPE VARCHAR(255),
	ELIGIBLE_PRICE_INCREASE VARCHAR(255),
	SUBSCRIPTION_STATUS VARCHAR(255),
	INITIAL_TERM NUMBER(12,0),
	INITIAL_TERM_PERIOD_TYPE VARCHAR(255),
	IS_INVOICE_SEPARATE BOOLEAN,
	NOTES VARCHAR(255),
	ORIGINAL_CREATE_SRC_DATE TIMESTAMP_NTZ(9),
	ORIGINAL_CREATE_DATE_UTC TIMESTAMP_NTZ(9),
	RENEWAL_SETTING VARCHAR(255),
	RENEWAL_TERM NUMBER(12,0),
	RENEWAL_TERM_PERIOD_TYPE VARCHAR(255),
	SERVICE_ACTIVATION_DATE TIMESTAMP_NTZ(9),
	SERVICE_ACTIVATION_DATE_UTC TIMESTAMP_NTZ(9),
	VERSION_STATUS VARCHAR(255),
	SUBSCRIPTION_END_DATE TIMESTAMP_NTZ(9),
	SUBSCRIPTION_END_DATE_UTC TIMESTAMP_NTZ(9),
	SUBSCRIPTION_START_DATE TIMESTAMP_NTZ(9),
	SUBSCRIPTION_START_DATE_UTC TIMESTAMP_NTZ(9),
	SUBSCRIPTION_TYPE VARCHAR(255),
	TERM_END_DATE TIMESTAMP_NTZ(9),
	TERM_END_DATE_UTC TIMESTAMP_NTZ(9),
	TERM_START_DATE TIMESTAMP_NTZ(9),
	TERM_START_DATE_UTC TIMESTAMP_NTZ(9),
	TERM_TYPE VARCHAR(255),
	WORKFLOW_ACTION VARCHAR(255),
	FREEZE_START_DATE TIMESTAMP_NTZ(9),
	FREEZE_START_DATE_UTC TIMESTAMP_NTZ(9),
	FREEZE_END_DATE TIMESTAMP_NTZ(9),
	FREEZE_END_DATE_UTC TIMESTAMP_NTZ(9),
	IS_MIGRATED BOOLEAN,
	OPPORTUNITY_CLOSE_DATE TIMESTAMP_NTZ(9),
	OPPORTUNITY_CLOSE_DATE_UTC TIMESTAMP_NTZ(9),
	OPPORTUNITY_NAME VARCHAR(255),
	PREVIOUS_SUBSCRIPTION_SRC_ID VARCHAR(255),
	UPDATEDDATE TIMESTAMP_NTZ(9),
	UPDATEDDATE_UTC TIMESTAMP_NTZ(9),
	IS_CURRENT_RECORD_FOR_3DAY BOOLEAN,
	CHECK7DAYS BOOLEAN,
	IS_3DAY_CANCEL_FLAG BOOLEAN,
	IS_SAME_DAY_CANCEL_FLAG BOOLEAN,
	PROMO_CODE VARCHAR(255),
	CORPORATE_CODE VARCHAR(255),
	ACCESS VARCHAR(255),
	BENEFIT VARCHAR(255),
	PT_SERVICE_DURATION VARCHAR(255),
	ORIG_SALES_CHANNEL VARCHAR(255),
	SALES_CHANNEL VARCHAR(10),
	SALES_TIMING VARCHAR(255),
	PRICING_PRODUCT_CODE VARCHAR(255),
	PRICE_REASON_CODE VARCHAR(255),
	CREATE_REASON VARCHAR(255),
	PREVIOUS_SUBSCRIPTION_SRC_NUM VARCHAR(255),
	PROJECT VARCHAR(255),
	SUB_PROJECT VARCHAR(255),
	IS_EXCLUDABLE_PROMO_FLAG VARCHAR(1),
	IS_CURRENT_RECORD BOOLEAN,
	SUBSCRIPTION_CURR_ID VARCHAR(32),
	SUBSCRIPTION_MERGE_ID VARCHAR(16777216),
	IS_AUTO_CANCEL BOOLEAN,
	AUDT_CREATE_DATE TIMESTAMP_NTZ(9),
	AUDT_UPDATE_DATE TIMESTAMP_NTZ(9),
	AUDT_USER_ID VARCHAR(17),
	AUDT_SRC_SYS_CODE VARCHAR(5),
	AUDT_BATCH_ID VARCHAR(36)
);

when using dim_subscription_new always use is_current_record = true;


Please create and sql that:

for each customer_id select the subscription_id with:
the latest effective_date and subscription type = ‘Membership’ 

avoid the use of inner queries use CTEs instead
            """,
        }
    ],
    "stream": False,
    "system": (
        "You are a SQL generator for snowflake. "
        "Only output the first raw SQL code. "
        "No conversational text, no explanations, no markdown formatting. "
        "the output should be able execute just as it is"
    ),
}

response = requests.post(url, json=payload, verify=False)
response.raise_for_status()

data = response.json()
#print(json.dumps(data, indent=2))

content = data["message"]["content"]
start = content.find("```sql\n")
if start != -1:
    start += len("```sql\n")
    end = content.find("```\n", start)
    if end == -1:
        end = content.find("```", start)
    sql = content[start:end]
    print(sql)
